// Auto-generated by Supabase TypeGen — do not edit manually
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      autovelox_omologati: {
        Row: {
          attivo: boolean
          costruttore: string | null
          created_at: string
          data_omologazione: string | null
          decreto_omologazione: string | null
          id: string
          modello: string
          note: string | null
          tipo: string | null
        }
        Insert: {
          attivo?: boolean
          costruttore?: string | null
          created_at?: string
          data_omologazione?: string | null
          decreto_omologazione?: string | null
          id?: string
          modello: string
          note?: string | null
          tipo?: string | null
        }
        Update: {
          attivo?: boolean
          costruttore?: string | null
          created_at?: string
          data_omologazione?: string | null
          decreto_omologazione?: string | null
          id?: string
          modello?: string
          note?: string | null
          tipo?: string | null
        }
        Relationships: []
      }
      consents: {
        Row: {
          accettato: boolean
          created_at: string
          id: string
          ip_address: unknown
          tipo: string
          user_agent: string | null
          user_id: string
        }
        Insert: {
          accettato?: boolean
          created_at?: string
          id?: string
          ip_address?: unknown
          tipo: string
          user_agent?: string | null
          user_id: string
        }
        Update: {
          accettato?: boolean
          created_at?: string
          id?: string
          ip_address?: unknown
          tipo?: string
          user_agent?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "consents_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      pratiche: {
        Row: {
          created_at: string
          id: string
          importo_pagato: number | null
          pagato_at: string | null
          pec_destinatario: string | null
          pec_inviata_at: string | null
          pec_message_id: string | null
          pec_ricevuta_at: string | null
          pec_stato: string | null
          piano: string | null
          ricorso_generato_at: string | null
          ricorso_pdf_path: string | null
          ricorso_pdf_url: string | null
          ricorso_testo: string | null
          stato: Database["public"]["Enums"]["stato_pratica"]
          stripe_checkout_session_id: string | null
          stripe_payment_intent_id: string | null
          updated_at: string
          user_id: string
          verbale_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          importo_pagato?: number | null
          pagato_at?: string | null
          pec_destinatario?: string | null
          pec_inviata_at?: string | null
          pec_message_id?: string | null
          pec_ricevuta_at?: string | null
          pec_stato?: string | null
          piano?: string | null
          ricorso_generato_at?: string | null
          ricorso_pdf_path?: string | null
          ricorso_pdf_url?: string | null
          ricorso_testo?: string | null
          stato?: Database["public"]["Enums"]["stato_pratica"]
          stripe_checkout_session_id?: string | null
          stripe_payment_intent_id?: string | null
          updated_at?: string
          user_id: string
          verbale_id: string
        }
        Update: {
          created_at?: string
          id?: string
          importo_pagato?: number | null
          pagato_at?: string | null
          pec_destinatario?: string | null
          pec_inviata_at?: string | null
          pec_message_id?: string | null
          pec_ricevuta_at?: string | null
          pec_stato?: string | null
          piano?: string | null
          ricorso_generato_at?: string | null
          ricorso_pdf_path?: string | null
          ricorso_pdf_url?: string | null
          ricorso_testo?: string | null
          stato?: Database["public"]["Enums"]["stato_pratica"]
          stripe_checkout_session_id?: string | null
          stripe_payment_intent_id?: string | null
          updated_at?: string
          user_id?: string
          verbale_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pratiche_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pratiche_verbale_id_fkey"
            columns: ["verbale_id"]
            isOneToOne: false
            referencedRelation: "verbali"
            referencedColumns: ["id"]
          },
        ]
      }
      prefetture: {
        Row: {
          created_at: string
          id: string
          indirizzo: string | null
          nome: string
          pec: string
          provincia: string
          telefono: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          indirizzo?: string | null
          nome: string
          pec: string
          provincia: string
          telefono?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          indirizzo?: string | null
          nome?: string
          pec?: string
          provincia?: string
          telefono?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          address: string | null
          avatar_url: string | null
          city: string | null
          created_at: string
          email: string | null
          fiscal_code: string | null
          full_name: string | null
          id: string
          phone: string | null
          province: string | null
          updated_at: string
          zip_code: string | null
        }
        Insert: {
          address?: string | null
          avatar_url?: string | null
          city?: string | null
          created_at?: string
          email?: string | null
          fiscal_code?: string | null
          full_name?: string | null
          id: string
          phone?: string | null
          province?: string | null
          updated_at?: string
          zip_code?: string | null
        }
        Update: {
          address?: string | null
          avatar_url?: string | null
          city?: string | null
          created_at?: string
          email?: string | null
          fiscal_code?: string | null
          full_name?: string | null
          id?: string
          phone?: string | null
          province?: string | null
          updated_at?: string
          zip_code?: string | null
        }
        Relationships: []
      }
      verbali: {
        Row: {
          articolo_cds: string | null
          comma: string | null
          comune: string | null
          created_at: string
          data_notifica: string | null
          data_violazione: string | null
          id: string
          image_path: string | null
          image_url: string | null
          importo: number | null
          importo_ridotto: number | null
          livello: Database["public"]["Enums"]["livello_contestabilita"] | null
          luogo: string | null
          modello_apparecchio: string | null
          numero_verbale: string | null
          ocr_raw_text: string | null
          ora_violazione: string | null
          organo_accertatore: string | null
          parsed_json: Json | null
          provincia: string | null
          punti_patente: number | null
          scadenza_pagamento_ridotto: string | null
          scadenza_ricorso_gdp: string | null
          scadenza_ricorso_prefetto: string | null
          score: number | null
          targa: string | null
          tipo_infrazione: Database["public"]["Enums"]["tipo_infrazione"]
          updated_at: string
          user_id: string
          velocita_consentita: number | null
          velocita_rilevata: number | null
          via: string | null
          vizi: Json | null
        }
        Insert: {
          articolo_cds?: string | null
          comma?: string | null
          comune?: string | null
          created_at?: string
          data_notifica?: string | null
          data_violazione?: string | null
          id?: string
          image_path?: string | null
          image_url?: string | null
          importo?: number | null
          importo_ridotto?: number | null
          livello?: Database["public"]["Enums"]["livello_contestabilita"] | null
          luogo?: string | null
          modello_apparecchio?: string | null
          numero_verbale?: string | null
          ocr_raw_text?: string | null
          ora_violazione?: string | null
          organo_accertatore?: string | null
          parsed_json?: Json | null
          provincia?: string | null
          punti_patente?: number | null
          scadenza_pagamento_ridotto?: string | null
          scadenza_ricorso_gdp?: string | null
          scadenza_ricorso_prefetto?: string | null
          score?: number | null
          targa?: string | null
          tipo_infrazione?: Database["public"]["Enums"]["tipo_infrazione"]
          updated_at?: string
          user_id: string
          velocita_consentita?: number | null
          velocita_rilevata?: number | null
          via?: string | null
          vizi?: Json | null
        }
        Update: {
          articolo_cds?: string | null
          comma?: string | null
          comune?: string | null
          created_at?: string
          data_notifica?: string | null
          data_violazione?: string | null
          id?: string
          image_path?: string | null
          image_url?: string | null
          importo?: number | null
          importo_ridotto?: number | null
          livello?: Database["public"]["Enums"]["livello_contestabilita"] | null
          luogo?: string | null
          modello_apparecchio?: string | null
          numero_verbale?: string | null
          ocr_raw_text?: string | null
          ora_violazione?: string | null
          organo_accertatore?: string | null
          parsed_json?: Json | null
          provincia?: string | null
          punti_patente?: number | null
          scadenza_pagamento_ridotto?: string | null
          scadenza_ricorso_gdp?: string | null
          scadenza_ricorso_prefetto?: string | null
          score?: number | null
          targa?: string | null
          tipo_infrazione?: Database["public"]["Enums"]["tipo_infrazione"]
          updated_at?: string
          user_id?: string
          velocita_consentita?: number | null
          velocita_rilevata?: number | null
          via?: string | null
          vizi?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "verbali_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      livello_contestabilita: "verde" | "giallo" | "rosso"
      stato_pratica:
        | "analisi"
        | "pagamento"
        | "generazione_ricorso"
        | "invio_pec"
        | "attesa_risposta"
        | "chiusa"
      tipo_infrazione:
        | "velocita"
        | "sosta"
        | "ztl"
        | "semaforo"
        | "telefono"
        | "altro"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Convenience type helpers
type DefaultSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  T extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"]),
> = (DefaultSchema["Tables"] & DefaultSchema["Views"])[T] extends {
  Row: infer R
}
  ? R
  : never

export type TablesInsert<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T] extends { Insert: infer I } ? I : never

export type TablesUpdate<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T] extends { Update: infer U } ? U : never

export type Enums<T extends keyof DefaultSchema["Enums"]> =
  DefaultSchema["Enums"][T]
